package models

import (
	"time"

	"gorm.io/gorm"
)

// DeveloperKey represents an API key generated by a user to integrate our gateway.
type DeveloperKey struct {
	ID         uint           `json:"id" gorm:"primaryKey"`
	UserID     uint           `json:"user_id" gorm:"index;not null"`
	User       User           `json:"-" gorm:"foreignKey:UserID"`
	Name       string         `json:"name" gorm:"not null"`
	KeyHash    string         `json:"-" gorm:"uniqueIndex;not null"` // SHA-256 hash of the API key
	MaskedKey  string         `json:"masked_key" gorm:"not null"`    // e.g., "luco_live_****1234"
	IsActive   bool           `json:"is_active" gorm:"default:true;index"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	LastUsedAt *time.Time     `json:"last_used_at"`
	DeletedAt  gorm.DeletedAt `json:"-" gorm:"index"`
}

// CreateDeveloperKeyRequest is the request body for creating a new developer API key.
type CreateDeveloperKeyRequest struct {
	Name string `json:"name" validate:"required,min=2"`
}

// CreateDeveloperKeyResponse returns the newly created API key details.
// This is the ONLY time the raw key is shown to the user.
type CreateDeveloperKeyResponse struct {
	ID        uint      `json:"id"`
	Name      string    `json:"name"`
	RawKey    string    `json:"raw_key"` // Shown only once
	MaskedKey string    `json:"masked_key"`
	CreatedAt time.Time `json:"created_at"`
}

// SMSJob represents an asynchronous SMS message processing job.
type SMSJob struct {
	ID           uint           `json:"id" gorm:"primaryKey"`
	UserID       uint           `json:"user_id" gorm:"index;not null"`
	User         User           `json:"-" gorm:"foreignKey:UserID"`
	Phone        string         `json:"phone" gorm:"not null"`
	Message      string         `json:"message" gorm:"not null"`
	Segments     int            `json:"segments" gorm:"not null;default:1"`
	Credits      int            `json:"credits" gorm:"not null;default:1"`
	Status       string         `json:"status" gorm:"not null;default:'pending';index"` // pending | processing | completed | failed
	ErrorMessage string         `json:"error_message"`
	Attempts     int            `json:"attempts" gorm:"not null;default:0"`
	CreatedAt    time.Time      `json:"created_at" gorm:"index"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    gorm.DeletedAt `json:"-" gorm:"index"`
}

// GatewaySendSMSRequest is the payload for client/developer applications to send SMS.
type GatewaySendSMSRequest struct {
	Phone   string   `json:"phone"`
	Phones  []string `json:"phones"`
	Message string   `json:"message" validate:"required"`
}

// GatewaySendSMSResponse is the response returned to client applications.
type GatewaySendSMSResponse struct {
	Success    bool   `json:"success"`
	Message    string `json:"message"`
	JobGroupID string `json:"job_group_id,omitempty"` // For checking status later
}
